name: closet
description: 2020 winter to 2021 Fall semester

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.0.1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+14
  flare_flutter: ^2.0.6
  geolocator: ^6.1.13
  geolocator_platform_interface: ^1.0.8
  location: ^3.2.4
  http: ^0.12.2
  animated_widgets: ^1.0.6
  animated_icon_button: ^0.3.0
  animate_icons: ^1.0.0
  cell_calendar: ^0.3.0
  image: ^2.1.4
  tflite: ^1.1.1
  font_awesome_flutter: ^8.11.0
  weather: ^1.2.4
  cached_network_image: ^2.5.0
  unicorndial: ^1.1.5
  file_picker: ^2.0.11
  flutter_search_bar: ^2.1.0
  table_calendar: ^2.3.3
  pie_chart: ^4.0.1
  backdrop: ^0.4.7
  intl: ^0.16.1
  sign_in_with_apple: ^2.5.4
  flutter_web_auth: ^0.2.4
  uuid: ^2.2.2
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path:
    - "assets/weather/sunny.png"
    - "assets/weather/cloudy.png"
    - "assets/weather/moon.png"
    - 'assets/weather/snow.png'
    - 'assets/weather/rain.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/1LMu.gif
    - assets/google_logo.png
    - assets/kakao_login_medium_narrow.png
    - assets/codi1.jpg
    - assets/codi2.jpg
    - assets/codi3.jpg
    - assets/codi4.jpg
    - assets/codi5.jpg
    - assets/codi6.jpg
    - assets/codi7.jpg
    - assets/codi8.jpg
    - assets/codi9.jpg
    - assets/top1.JPG
    - assets/top2.JPG
    - assets/bottom1.JPG
    - assets/bottom2.JPG
    - assets/bottom3.JPG
    - assets/sho1.JPG
    - assets/sho2.JPG
    - assets/switch_daytime.flr
    - assets/sample.png
    - assets/profile.jpg
    - assets/ml/mobilenet_v1_1.0_224.txt
    - assets/ml/mobilenet_v1_1.0_224.tflite
    - assets/weather/sunny.png
    - assets/weather/cloudy.png
    - assets/weather/moon.png
    - assets/weather/rain.png
    - assets/weather/snow.png
    - assets/weather/background_snow.png
    - assets/login/kakao.png
    - assets/login/naver.png
    - assets/login/facebook.png
    - assets/login/apple.png
    - assets/login/google.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700
    - family: Sansita
      fonts:
        - asset: assets/fonts/Sansita-ExtraBoldItalic.ttf
          weight: 800

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
